### ISSUE TITLE
WebUI

### ISSUE THREAD

**Issue by Pegasus8** [Pegasus8/PiWorker#7]
## To-do list

- [x] Design
- [ ] Visual development 
   - [ ] General development
   - [x] Compatibility
      - [x] Add `normalize.css`
      - [x] Add `modernizr.js`
      - [x] Bootstrap
- [ ] Live statistics
   - [x] WebSocket
   - [ ] Web elements update
   - [ ] Animations on update
- [ ] Login (#3)
- [ ] General animations
