### ISSUE TITLE
Dynamic Engine

### ISSUE THREAD

**Issue by Pegasus8** [Pegasus8/PiWorker#8]
## Description
Dynamic processing engine. It's the responsible for executing tasks and actions of the most optimal way.

## To-do list
- [x] Data reading on every round of loop. Reason: keep working with fresh data. Can be optimized but isn't a priority
- [x] Usage of pointers for lowest usage of memory possible (carefully)
- [x] ~~Execution queue: when a task is on process of execution (triggered) keep it on a queue, out of the rest of active tasks for prevention of multiple execution.~~ Change the state when the task starts the execution and when the execution ends (usage of `on-execution` state). 
- [x] Actions execution on another goroutine
- [x] Chained actions (tasks) (#12)
- [x] Ignore tasks with the state `completed`, `inactive` and `on-execution`
